/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.event.KeyListener;

/**
 *
 * @author Alexa
 */
public class NoughtsAndСrosses extends javax.swing.JFrame {

    /**
     * Creates new form NoughtsAndСrosses
     */
    Logic logic;
    Player player;
    Player ai;
    boolean clickState[] = new boolean[9];

    public NoughtsAndСrosses() {
        player = new Player("You", false, false, 'X');
        ai = new Player("AI", true, false, 'O');
        logic = new Logic(player, ai, false, new int[]{0, 0, 0, 0, 0, 0, 0, 0, 0});

        initComponents();

        f1.setText(" ");
        f2.setText(" ");
        f3.setText(" ");
        f4.setText(" ");
        f5.setText(" ");
        f6.setText(" ");
        f7.setText(" ");
        f8.setText(" ");
        f9.setText(" ");

        f1.setHighlighter(null);
        f2.setHighlighter(null);
        f3.setHighlighter(null);
        f4.setHighlighter(null);
        f5.setHighlighter(null);
        f6.setHighlighter(null);
        f7.setHighlighter(null);
        f8.setHighlighter(null);
        f9.setHighlighter(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restartBtn = new javax.swing.JButton();
        f1 = new javax.swing.JTextField();
        f2 = new javax.swing.JTextField();
        f3 = new javax.swing.JTextField();
        f4 = new javax.swing.JTextField();
        f5 = new javax.swing.JTextField();
        f6 = new javax.swing.JTextField();
        f7 = new javax.swing.JTextField();
        f8 = new javax.swing.JTextField();
        f9 = new javax.swing.JTextField();
        winField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnX = new javax.swing.JButton();
        btnO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        restartBtn.setBackground(new java.awt.Color(170, 100, 50));
        restartBtn.setText("RESTART");
        restartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartBtnActionPerformed(evt);
            }
        });

        f1.setEditable(false);
        f1.setBackground(new java.awt.Color(170, 100, 50));
        f1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        f1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f1.setText("X");
        f1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f1MouseClicked(evt);
            }
        });
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });

        f2.setEditable(false);
        f2.setBackground(new java.awt.Color(170, 100, 50));
        f2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        f2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f2.setText("X");
        f2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f2MouseClicked(evt);
            }
        });
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });

        f3.setEditable(false);
        f3.setBackground(new java.awt.Color(170, 100, 50));
        f3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        f3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f3.setText("X");
        f3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f3MouseClicked(evt);
            }
        });
        f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3ActionPerformed(evt);
            }
        });

        f4.setEditable(false);
        f4.setBackground(new java.awt.Color(170, 100, 50));
        f4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        f4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f4.setText("X");
        f4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f4MouseClicked(evt);
            }
        });
        f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f4ActionPerformed(evt);
            }
        });

        f5.setEditable(false);
        f5.setBackground(new java.awt.Color(170, 100, 50));
        f5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        f5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f5.setText("X");
        f5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f5MouseClicked(evt);
            }
        });
        f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f5ActionPerformed(evt);
            }
        });

        f6.setEditable(false);
        f6.setBackground(new java.awt.Color(170, 100, 50));
        f6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        f6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f6.setText("X");
        f6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f6MouseClicked(evt);
            }
        });
        f6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f6ActionPerformed(evt);
            }
        });

        f7.setEditable(false);
        f7.setBackground(new java.awt.Color(170, 100, 50));
        f7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        f7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f7.setText("X");
        f7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f7MouseClicked(evt);
            }
        });
        f7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f7ActionPerformed(evt);
            }
        });

        f8.setEditable(false);
        f8.setBackground(new java.awt.Color(170, 100, 50));
        f8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        f8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f8.setText("X");
        f8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f8MouseClicked(evt);
            }
        });
        f8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f8ActionPerformed(evt);
            }
        });

        f9.setEditable(false);
        f9.setBackground(new java.awt.Color(170, 100, 50));
        f9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        f9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f9.setText("X");
        f9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f9MouseClicked(evt);
            }
        });
        f9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f9ActionPerformed(evt);
            }
        });

        jLabel3.setText("Начните игру или выберите:");

        btnX.setBackground(new java.awt.Color(170, 100, 50));
        btnX.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnX.setText("X");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        btnO.setBackground(new java.awt.Color(170, 100, 50));
        btnO.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnO.setText("O");
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(f5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(f6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(f7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(winField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnO)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(175, 175, 175)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed

    }//GEN-LAST:event_f1ActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f2ActionPerformed

    private void f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f3ActionPerformed

    private void f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f4ActionPerformed

    private void f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f5ActionPerformed

    private void f6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f6ActionPerformed

    private void f7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f7ActionPerformed

    private void f8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f8ActionPerformed

    private void f9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f9ActionPerformed

    private void restartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartBtnActionPerformed
        f1.setText(" ");
        f2.setText(" ");
        f3.setText(" ");
        f4.setText(" ");
        f5.setText(" ");
        f6.setText(" ");
        f7.setText(" ");
        f8.setText(" ");
        f9.setText(" ");

        logic.setBoard(new int[]{0, 0, 0, 0, 0, 0, 0, 0, 0});
        logic.setEndOfGame(false);

        btnX.setEnabled(true);
        btnO.setEnabled(true);
        winField.setText(" ");
    }//GEN-LAST:event_restartBtnActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        player.setFigure('X');
        player.setMadeStep(false);
        ai.setFigure('O');
        ai.setMadeStep(true);
        btnX.setEnabled(false);
        btnO.setEnabled(false);
    }//GEN-LAST:event_btnXActionPerformed

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
        player.setFigure('O');
        player.setMadeStep(true);
        ai.setFigure('X');
        ai.setMadeStep(false);
        btnX.setEnabled(false);
        btnO.setEnabled(false);
        //сделать ход компом
        logic.makeStep();
        printAiMove(logic.getBoard());

    }//GEN-LAST:event_btnOActionPerformed

    private void printAiMove(int[] board) {
        if (ai.getFigure() == 'X') {
            for (int i = 0; i < board.length; i++) {
                if (board[i] == -1) {
                    switch (i) {
                        case 0:
                            f1.setText("X");
                            break;
                        case 1:
                            f2.setText("X");
                            break;
                        case 2:
                            f3.setText("X");
                            break;
                        case 3:
                            f4.setText("X");
                            break;
                        case 4:
                            f5.setText("X");
                            break;
                        case 5:
                            f6.setText("X");
                            break;
                        case 6:
                            f7.setText("X");
                            break;
                        case 7:
                            f8.setText("X");
                            break;
                        case 8:
                            f9.setText("X");
                            break;

                    }
                }
            }
        } else if (ai.getFigure() == 'O') {
            for (int i = 0; i < board.length; i++) {
                if (board[i] == -1) {
                    switch (i) {
                        case 0:
                            f1.setText("O");
                            break;
                        case 1:
                            f2.setText("O");
                            break;
                        case 2:
                            f3.setText("O");
                            break;
                        case 3:
                            f4.setText("O");
                            break;
                        case 4:
                            f5.setText("O");
                            break;
                        case 5:
                            f6.setText("O");
                            break;
                        case 6:
                            f7.setText("O");
                            break;
                        case 7:
                            f8.setText("O");
                            break;
                        case 8:
                            f9.setText("O");
                            break;

                    }
                }
            }
        }
    }

    private void processGame() {
        btnX.setEnabled(false);
        btnO.setEnabled(false);
        player.setMadeStep(true);
        ai.setMadeStep(false);
        logic.makeStep();
        printAiMove(logic.getBoard());
        int rez = logic.checkWin(logic.getBoard());
        if (rez == 1) {
            winField.setText("You won! Restart...");
        } else if (rez == -1) {
            winField.setText("Ai won! Restart...");
        } else if (rez == 0) {
            winField.setText("Draw! Restart...");
        }
    }

    //игрок походил
    private void f1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1MouseClicked
        if (logic.checkBoardPosition(logic.getBoard(), 0) && !logic.isEndOfGame()) {
            f1.setText(Character.toString(player.getFigure()));
            logic.setBoardValue(logic.getBoard(), 0, 1);
            processGame();
        }
    }//GEN-LAST:event_f1MouseClicked

    private void f2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f2MouseClicked
        if (logic.checkBoardPosition(logic.getBoard(), 1) && !logic.isEndOfGame()) {
            f2.setText(Character.toString(player.getFigure()));
            logic.setBoardValue(logic.getBoard(), 1, 1);
            processGame();
        }
    }//GEN-LAST:event_f2MouseClicked

    private void f3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f3MouseClicked
        if (logic.checkBoardPosition(logic.getBoard(), 2) && !logic.isEndOfGame()) {
            f3.setText(Character.toString(player.getFigure()));
            logic.setBoardValue(logic.getBoard(), 2, 1);
            processGame();
        }
    }//GEN-LAST:event_f3MouseClicked

    private void f4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f4MouseClicked
        if (logic.checkBoardPosition(logic.getBoard(), 3) && !logic.isEndOfGame()) {
            f4.setText(Character.toString(player.getFigure()));
            logic.setBoardValue(logic.getBoard(), 3, 1);
            processGame();
        }
    }//GEN-LAST:event_f4MouseClicked

    private void f5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f5MouseClicked
        if (logic.checkBoardPosition(logic.getBoard(), 4) && !logic.isEndOfGame()) {
            f5.setText(Character.toString(player.getFigure()));
            logic.setBoardValue(logic.getBoard(), 4, 1);
            processGame();
        }
    }//GEN-LAST:event_f5MouseClicked

    private void f6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f6MouseClicked
        if (logic.checkBoardPosition(logic.getBoard(), 5) && !logic.isEndOfGame()) {
            f6.setText(Character.toString(player.getFigure()));
            logic.setBoardValue(logic.getBoard(), 5, 1);
            processGame();
        }
    }//GEN-LAST:event_f6MouseClicked

    private void f7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f7MouseClicked
        if (logic.checkBoardPosition(logic.getBoard(), 6) && !logic.isEndOfGame()) {
            f7.setText(Character.toString(player.getFigure()));
            logic.setBoardValue(logic.getBoard(), 6, 1);
            processGame();
        }
    }//GEN-LAST:event_f7MouseClicked

    private void f8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f8MouseClicked
        if (logic.checkBoardPosition(logic.getBoard(), 7) && !logic.isEndOfGame()) {
            f8.setText(Character.toString(player.getFigure()));
            logic.setBoardValue(logic.getBoard(), 7, 1);
            processGame();
        }
    }//GEN-LAST:event_f8MouseClicked

    private void f9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f9MouseClicked
        if (logic.checkBoardPosition(logic.getBoard(), 8) && !logic.isEndOfGame()) {
            f9.setText(Character.toString(player.getFigure()));
            logic.setBoardValue(logic.getBoard(), 8, 1);
            processGame();
        }
    }//GEN-LAST:event_f9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoughtsAndСrosses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoughtsAndСrosses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoughtsAndСrosses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoughtsAndСrosses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NoughtsAndСrosses сrosses = new NoughtsAndСrosses();
                сrosses.setLocationRelativeTo(null);
                сrosses.setTitle("NoughtsAndCrosees");
                сrosses.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnX;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField f4;
    private javax.swing.JTextField f5;
    private javax.swing.JTextField f6;
    private javax.swing.JTextField f7;
    private javax.swing.JTextField f8;
    private javax.swing.JTextField f9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton restartBtn;
    private javax.swing.JTextField winField;
    // End of variables declaration//GEN-END:variables
}
